apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: petclinic-gateway
  namespace: petclinic
spec:
  selector:
    istio: ingressgateway # chỉ định rằng cấu hình này sẽ được áp dụng lên Pod istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP 
    hosts:
    - "*" # Cho phép truy cập từ bất kỳ tên miền hoặc địa chỉ IP nào
