apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default-permissive
  namespace: petclinic
spec:
  mtls:
    mode: PERMISSIVE # Cho phép cả mTLS và kết nối không mTLS trong namespace