apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: customers-port-fix
  namespace: petclinic
spec:
  hosts:
  - customers-service.petclinic.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - number: 80 # Cổng mà Java gọi tới
    name: http
    protocol: HTTP
    targetPort: 8081 # Cổng thực tế ứng dụng đang chạy
  resolution: DNS