apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: petclinic
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        version: v1
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: api-gateway
        image: docker.io/tnnhan57/api-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: CONFIG_SERVER_URL
          value: "http://config-server:8888"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "false"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "false"

        - name: SPRING_CLOUD_GATEWAY_ROUTES_0_ID
          value: "vets-service"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
          value: "http://vets-service:8083"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0
          value: "Path=/api/vet/**"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_0_FILTERS_0
          value: "StripPrefix=2"

        - name: SPRING_CLOUD_GATEWAY_ROUTES_1_ID
          value: "visits-service"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
          value: "http://visits-service:8082"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0
          value: "Path=/api/visit/**"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_1_FILTERS_0
          value: "StripPrefix=2"

        - name: SPRING_CLOUD_GATEWAY_ROUTES_2_ID
          value: "customers-service"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_2_URI
          value: "http://customers-service:8081"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0
          value: "Path=/api/customer/**"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_2_FILTERS_0
          value: "StripPrefix=2"

        - name: CUSTOMERS_SERVICE_URL
          value: "http://customers-service:8081"
        - name: VETS_SERVICE_URL
          value: "http://vets-service:8083"
        - name: VISITS_SERVICE_URL
          value: "http://visits-service:8082"
        - name: SPRING_CLOUD_LOADBALANCER_ENABLED
          value: "false"
        - name: SPRING_CLOUD_LOADBALANCER_RIBBON_ENABLED
          value: "false"
